---
- name: Env_init
  hosts: all
  roles:
    - env_init

- name: Run bootstrap on the first monitor node
  hosts: ceph_bootstrap
  roles:
    - run_bootstrap

- name: Add hosts to the cluster
  hosts: new_add_ceph_nodes
  roles:
    - add_host

- name: Add storage to the cluster
  hosts: ceph_bootstrap
  roles:
    - add_storage
